version: '3.4'

services:
  starwars_db:
    image: mysql:8.0
    restart: always
    volumes:
      - starwars_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starwars_db
    ports:
      - 3306:3306

volumes:
  starwars_db:
    driver: "local"